### ISSUE TITLE
Documentation on choosing MMTracking for object tracking

### ISSUE THREAD

**Issue by SoniaGrh** [picselliahq/picsellia-training-engine#101]
**As a** Data Scientist,
**I want to** write detailed documentation explaining why MMTracking was chosen for our object tracking needs,
**So that** I can provide a solid justification for this choice in terms of performance, efficiency, and ease of integration into our workflows.

**Acceptance Criteria:**
- [x] The documentation presents a detailed comparison of MMTracking with other options, highlighting the reasons for our choice.
- [x] The documentation presents a detailed comparison of MMTracking's model options, highlighting the reasons this specific model.

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] Documentation is updated.

**Comment by SoniaGrh** [comment]
[Notion documentation](https://www.notion.so/picsellia/Object-Tracking-b1a51af624f24bd8ad4b81b43cc8e6b1)
